### ISSUE TITLE
Changing the nms_cred_path breaks NMS

### ISSUE THREAD

**Issue by nginx-danieloc** [nginxinc/ansible-role-nginx-management-suite#48]
### Describe the bug

The `nms_cred_path` cannot be changed. If it is then NGINX in front of NMS cannot find the password file. 

### To reproduce

1. Create a playbook like the following
```
- hosts: nms
  become: yes
  vars:
    nginx_license:
      certificate: ./nginx-repo.crt
      key: ./nginx-repo.key
    nms_setup: install
    nms_cred_path: /etc/.htpasswd
  collections:
    - nginxinc.nginx_core
  roles:
    - ansible-role-nginx-management-suite
```
2. Deploy the Ansible NGINX Management Suite role using `playbook.yml`

### Expected behavior

NMS works after setting variables

### Your environment

- Version of the Ansible NGINX Management Suite role or specific commit - 0.3.0
- Version of Ansible - 2.12
